# Generated by Django 5.0 on 2023-12-06 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depanneur',
            fields=[
                ('MechanicID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Statut', models.CharField(max_length=100)),
                ('Specialites', models.CharField(max_length=255)),
                ('Position_geographique_latitude', models.FloatField()),
                ('Position_geographique_longitude', models.FloatField()),
                ('Evaluation_moyenne', models.FloatField()),
                ('Types_vehicules_depannage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Destinataire', models.CharField(max_length=100)),
                ('Contenu_de_la_notification', models.TextField()),
                ('Date_et_heure_denvoi', models.DateTimeField(auto_now_add=True)),
                ('Statut', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesDeDepannage',
            fields=[
                ('ServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_du_service', models.CharField(max_length=100)),
                ('Description_du_service', models.TextField()),
                ('Cout_du_service', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('Adresse_email', models.EmailField(max_length=254, unique=True)),
                ('Mot_de_passe', models.CharField(max_length=255)),
                ('Numero_de_telephone', models.CharField(max_length=15)),
                ('Adresse_physique', models.TextField()),
                ('Type_utilisateur', models.CharField(max_length=50)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('PricingID', models.AutoField(primary_key=True, serialize=False)),
                ('Cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Is_active', models.BooleanField(default=True)),
                ('MechanicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.depanneur')),
                ('ServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.servicesdedepannage')),
            ],
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_et_heure_de_la_transaction', models.DateTimeField(auto_now_add=True)),
                ('Statut', models.CharField(max_length=100)),
                ('Utilisateur_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='AvisEtEvaluations',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('Note', models.FloatField()),
                ('Commentaire', models.TextField()),
                ('Date_de_lavis', models.DateTimeField(auto_now_add=True)),
                ('Depanneur_evalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.depanneur')),
                ('Utilisateur_evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculesDeDepannage',
            fields=[
                ('TowTruckID', models.AutoField(primary_key=True, serialize=False)),
                ('Modele_de_vehicule', models.CharField(max_length=100)),
                ('Annee_de_fabrication', models.IntegerField()),
                ('Plaque_dimmatriculation', models.CharField(max_length=20)),
                ('Capacite_de_remorquage', models.FloatField()),
                ('Statut', models.CharField(max_length=100)),
                ('MechanicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.depanneur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDesDepannages',
            fields=[
                ('HistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Position_geographique_latitude', models.FloatField()),
                ('Position_geographique_longitude', models.FloatField()),
                ('Description_de_la_panne', models.TextField()),
                ('Cout_du_depannage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_et_heure_du_depannage', models.DateTimeField(auto_now_add=True)),
                ('Statut_du_depannage', models.CharField(max_length=100)),
                ('Depanneur_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.depanneur')),
                ('Type_de_service_fourni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.servicesdedepannage')),
                ('Utilisateur_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.users')),
                ('Vehicule_de_depannage_utilise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.vehiculesdedepannage')),
            ],
        ),
        migrations.CreateModel(
            name='DemandesDeDepannage',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('Position_geographique_latitude', models.FloatField()),
                ('Position_geographique_longitude', models.FloatField()),
                ('Description_de_la_panne', models.TextField()),
                ('Statut_de_la_demande', models.CharField(max_length=100)),
                ('Date_et_heure_de_la_demande', models.DateTimeField(auto_now_add=True)),
                ('Depanneur_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonApp.depanneur')),
                ('Type_de_service_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.servicesdedepannage')),
                ('Utilisateur_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonApp.users')),
                ('Vehicule_de_depannage_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonApp.vehiculesdedepannage')),
            ],
        ),
    ]
